package main

import (
	"log"
	"net/http"

	"github.com/gorilla/mux"
	_ "github.com/kyfelipe/correios-api/docs" // docs is generated by Swag CLI, you have to import it.
	"github.com/kyfelipe/correios-api/services"
	httpSwagger "github.com/swaggo/http-swagger"
)

// @title Correios API
// @version 1.0
// @description TO-DO.
// @termsOfService http://swagger.io/terms/

// @contact.name Felipe Côrtes
// @contact.url http://www.fcortes.com.br/
// @contact.email contatos.cortes@gmail.com

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @host localhost:4000
// @BasePath /

// https://apps.correios.com.br/SigepMasterJPA/AtendeClienteService/AtendeCliente?wsdl
func main() {
	router := mux.NewRouter()
	// Consulta cep
	router.HandleFunc("/consultaCEP", services.ConsultaCEP).Methods("GET")

	router.PathPrefix("/swagger").Handler(httpSwagger.WrapHandler)
	log.Fatal(http.ListenAndServe(":4000", router))
}
