# https://help.github.com/pt/actions/reference/workflow-syntax-for-github-actions
name: Build and push image

on:
  push:
    tags:

jobs:
  build-push:
    name: Build and Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Fetch origin/master from Git
        run: git fetch origin master
      - name: Build Docker image
        run: docker build -t correios-api .
      - name: Deploy the tagged Docker image to Docker Hub
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          api_version=${GITHUB_REF:10}
          docker login -u kyfelipe -p ${{secrets.DOCKER_PASSWORD}}
          docker tag correios-api "kyfelipe/correios-api:$api_version"
          docker push "kyfelipe/correios-api:$api_version"
          docker tag correios-api "kyfelipe/correios-api:latest"
          docker push "kyfelipe/correios-api:latest"
