# https://help.github.com/pt/actions/reference/workflow-syntax-for-github-actions
name: Build and Push image

on:
  push:
    tags:

jobs:
  build-push:
    name: Build and Push
    runs-on:
      - self-hosted
      - linux
    steps:
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: kyfelipe/correios-api
          tags: latest
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: kyfelipe/correios-api
          tag_with_ref: true
          push: ${{ startsWith(github.ref, 'refs/tags/') }}
